### ISSUE TITLE
possibly syntax error in callback_registry.rb:15

### ISSUE THREAD

**Issue by Unayung** [tinkerbox/message_quickly#3]
I'm not sure if it's me or what. but when I hit rails s right after installed this gem.
I got this error.
thanks for creating this gem :)

![2016-05-29 14 20 43](https://cloud.githubusercontent.com/assets/1853105/15631687/926d85ce-25a8-11e6-91df-ed19a3de62df.png)

**Comment by jaryl** [comment]
It looks like your webhook wasn't registered. Have you run the following:

`rails generate message_quickly:callbacks`

If have already done so then you may need to restart your server.

**Comment by jaryl** [comment]
Hmm, ah, it looks like you are using ruby 2.1, which doesn't support the safe navigation operator. I will see if I can rewrite the code not to use it.

**Comment by Unayung** [comment]
wow. thanks for the quick reply. I will using 2.2 to see if it's work though.
thank you :)

EDIT: just checked safe navigation operator. it's start from 2.3.0 so I will switch to 2.3.0 then.
